# Generated by Django 4.1.7 on 2023-03-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_', '0002_alter_lead_summ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='summ',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
